package psychlua.backend.actorframe;

#if LUA_ALLOWED
class ActorFrameLuaPrelude
{
	public static function prelude():String
	{
		return [
			"Def = Def or {}",
			"ActorFrame = ActorFrame or { Roots = {}, Actors = {}, _counter = 0, _tweenCounter = 0 }",
			"local AF = ActorFrame",
			"local function sanitize(name)",
			"  name = tostring(name or '')",
			"  name = name:gsub('^%s+', ''):gsub('%s+$', '')",
			"  if name == '' then name = 'actor' .. tostring(AF._counter + 1) end",
			"  return (name:gsub('[^%w_%-]', '_'))",
			"end",
			"local function def(kind)",
			"  return function(t)",
			"    if type(t) == 'string' then t = { File = t } end",
			"    t = t or {}",
			"    t.__ActorFrameKind = kind",
			"    return t",
			"  end",
			"end",
			"Def.ActorFrame = Def.ActorFrame or def('ActorFrame')",
			"Def.Sprite = Def.Sprite or def('Sprite')",
			"Def.Quad = Def.Quad or def('Quad')",
			"Def.Text = Def.Text or def('Text')",
			"Def.ActorProxy = Def.ActorProxy or def('ActorProxy')",
			"Def.ActorFrameTexture = Def.ActorFrameTexture or def('ActorFrameTexture')",
			"LoadActor = LoadActor or function(path)",
			"  return function(t)",
			"    t = t or {}",
			"    t.File = t.File or t.file or path",
			"    t.__ActorFrameKind = t.__ActorFrameKind or 'Sprite'",
			"    return t",
			"  end",
			"end",
			"LoadFont = LoadFont or function(path)",
			"  return function(t)",
			"    t = t or {}",
			"    t.Font = t.Font or t.font or path",
			"    t.__ActorFrameKind = t.__ActorFrameKind or 'Text'",
			"    return t",
			"  end",
			"end",
			"Def.ProxyWall = Def.ProxyWall or function(t)",
			"  t = t or {}",
			"  local count = tonumber(t.Count or t.count or 24) or 24",
			"  local spacing = tonumber(t.Spacing or t.spacing or 256) or 256",
			"  local startX = tonumber(t.StartX or t.startX or 500) or 500",
			"  local texture = t.Texture or t.texture or t.File or t.file",
			"  local root = { Name = t.Name or 'proxwall', Camera = t.Camera or t.camera or 'hud', __ActorFrameKind = 'ActorFrame', __ActorFrameProxyWall = true }",
			"  for i = 1, count do",
			"    root[#root + 1] = Def.Sprite { Name = 'proxy' .. tostring(i), Texture = texture, X = startX - spacing * i, Y = t.Y or t.y or 0, Alpha = t.Alpha or t.alpha or 1, Visible = t.Visible ~= false, Blend = t.Blend or t.blend }",
			"  end",
			"  return root",
			"end",
			"local methods = {}",
			"local function publishName(actor)",
			"  if not actor or not actor.Name then return end",
			"  local name = tostring(actor.Name)",
			"  AF.Actors[name] = actor",
			"  rawset(_G, name, actor)",
			"  local tableName, index = name:match('^([%w_]+)%[(%d+)%]$')",
			"  if tableName and index then",
			"    local bucket = rawget(_G, tableName)",
			"    if type(bucket) ~= 'table' then bucket = {}; rawset(_G, tableName, bucket) end",
			"    bucket[tonumber(index)] = actor",
			"  end",
			"end",
			"local function asCommand(commands)",
			"  return function(self)",
			"    return self:cmd(commands)",
			"  end",
			"end",
			"cmd = cmd or asCommand",
			"local function setImmediate(self, prop, value)",
			"  _actorFrameSet(self.Tag, prop, value)",
			"end",
			"local function getImmediate(self, prop)",
			"  return _actorFrameGet(self.Tag, prop)",
			"end",
			"local function tween(self, values)",
			"  if self._duration and (self._duration > 0 or self._delay > 0) then",
			"    for k, v in pairs(values) do _actorFrameTween(self.Tag, k, v, self._duration or 0, self._ease or 'linear', self._delay or 0) end",
			"    self._delay = (self._delay or 0) + (self._duration or 0)",
			"  else",
			"    for k, v in pairs(values) do setImmediate(self, k, v) end",
			"  end",
			"  return self",
			"end",
			"function methods:sleep(t) self._delay = (self._delay or 0) + (tonumber(t) or 0); return self end",
			"function methods:linear(t) self._duration = tonumber(t) or 0; self._ease = 'linear'; return self end",
			"function methods:decelerate(t) self._duration = tonumber(t) or 0; self._ease = 'decelerate'; return self end",
			"function methods:accelerate(t) self._duration = tonumber(t) or 0; self._ease = 'accelerate'; return self end",
			"function methods:bouncebegin(t) self._duration = tonumber(t) or 0; self._ease = 'bounceIn'; return self end",
			"function methods:bounceend(t) self._duration = tonumber(t) or 0; self._ease = 'bounceOut'; return self end",
			"function methods:spring(t) self._duration = tonumber(t) or 0; self._ease = 'elasticOut'; return self end",
			"function methods:x(v) return tween(self, {x = v}) end",
			"function methods:SetX(v) return self:x(v) end",
			"function methods:addx(v) return self:x((tonumber(self:GetX()) or 0) + (tonumber(v) or 0)) end",
			"function methods:AddX(v) return self:addx(v) end",
			"function methods:y(v) return tween(self, {y = v}) end",
			"function methods:SetY(v) return self:y(v) end",
			"function methods:addy(v) return self:y((tonumber(self:GetY()) or 0) + (tonumber(v) or 0)) end",
			"function methods:AddY(v) return self:addy(v) end",
			"function methods:z(v) return tween(self, {z = v}) end",
			"function methods:SetZ(v) return self:z(v) end",
			"function methods:addz(v) return self:z((tonumber(self:GetZ()) or 0) + (tonumber(v) or 0)) end",
			"function methods:AddZ(v) return self:addz(v) end",
			"function methods:xy(x, y) return tween(self, {x = x, y = y}) end",
			"function methods:SetXY(x, y) return self:xy(x, y) end",
			"function methods:zoom(v) return tween(self, {zoom = v}) end",
			"function methods:SetZoom(v) return self:zoom(v) end",
			"function methods:zoomx(v) return tween(self, {zoomx = v}) end",
			"function methods:SetZoomX(v) return self:zoomx(v) end",
			"function methods:zoomy(v) return tween(self, {zoomy = v}) end",
			"function methods:SetZoomY(v) return self:zoomy(v) end",
			"function methods:basezoom(v) return self:zoom(v) end",
			"function methods:basezoomx(v) return self:zoomx(v) end",
			"function methods:basezoomy(v) return self:zoomy(v) end",
			"function methods:zoomto(w, h) setImmediate(self, 'width', w); setImmediate(self, 'height', h); return self end",
			"function methods:zoomtowidth(w) setImmediate(self, 'width', w); return self end",
			"function methods:zoomtoheight(h) setImmediate(self, 'height', h); return self end",
			"function methods:stretchto(l, t, r, b) self:x(((tonumber(l) or 0) + (tonumber(r) or 0)) * 0.5); self:y(((tonumber(t) or 0) + (tonumber(b) or 0)) * 0.5); return self:zoomto((tonumber(r) or 0) - (tonumber(l) or 0), (tonumber(b) or 0) - (tonumber(t) or 0)) end",
			"function methods:rotationx(v) return tween(self, {rotationx = v}) end",
			"function methods:SetRotationX(v) return self:rotationx(v) end",
			"function methods:rotationy(v) return tween(self, {rotationy = v}) end",
			"function methods:SetRotationY(v) return self:rotationy(v) end",
			"function methods:rotationz(v) return tween(self, {angle = v}) end",
			"function methods:SetRotationZ(v) return self:rotationz(v) end",
			"function methods:rotation(v) return self:rotationz(v) end",
			"function methods:addrotationz(v) return self:rotationz((tonumber(self:GetRotationZ()) or 0) + (tonumber(v) or 0)) end",
			"function methods:AddRotationZ(v) return self:addrotationz(v) end",
			"function methods:diffusealpha(v) return tween(self, {alpha = v}) end",
			"function methods:SetDiffuseAlpha(v) return self:diffusealpha(v) end",
			"function methods:text(v) setImmediate(self, 'text', v); return self end",
			"function methods:SetText(v) return self:text(v) end",
			"function methods:visible(v) setImmediate(self, 'visible', v); return self end",
			"function methods:SetVisible(v) return self:visible(v) end",
			"function methods:hidden(v) setImmediate(self, 'hidden', v == nil or v == true or v == 1); return self end",
			"function methods:SetHidden(v) return self:hidden(v) end",
			"function methods:diffuse(r, g, b, a) _actorFrameSetColor(self.Tag, r, g, b, a); return self end",
			"function methods:SetDiffuse(r, g, b, a) return self:diffuse(r, g, b, a) end",
			"function methods:blend(v) setImmediate(self, 'blend', v); return self end",
			"function methods:additiveblend(v) if v == nil or v then setImmediate(self, 'blend', 'add') else setImmediate(self, 'blend', 'normal') end; return self end",
			"function methods:aux(v) return tween(self, {aux = v}) end",
			"function methods:getaux() return getImmediate(self, 'aux') or 0 end",
			"function methods:GetName() return self.Name end",
			"function methods:GetParent() return self.Parent end",
			"function methods:GetChildren() return self.Children end",
			"function methods:GetChild(name)",
			"  name = tostring(name or '')",
			"  for _, child in ipairs(self.Children or {}) do",
			"    if tostring(child.Name or '') == name or tostring(child.Tag or '') == name or tostring(child.Tag or ''):match('%.' .. name .. '$') then return child end",
			"  end",
			"  return AF.get(name)",
			"end",
			"function methods:GetX() return getImmediate(self, 'x') or 0 end",
			"function methods:GetY() return getImmediate(self, 'y') or 0 end",
			"function methods:GetZ() return getImmediate(self, 'z') or 0 end",
			"function methods:GetZoom() return getImmediate(self, 'zoom') or 1 end",
			"function methods:GetZoomX() return getImmediate(self, 'zoomx') or 1 end",
			"function methods:GetZoomY() return getImmediate(self, 'zoomy') or 1 end",
			"function methods:GetRotationZ() return getImmediate(self, 'rotationz') or 0 end",
			"function methods:GetAlpha() return getImmediate(self, 'alpha') or 1 end",
			"function methods:GetDiffuseAlpha() return self:GetAlpha() end",
			"function methods:GetVisible() return getImmediate(self, 'visible') end",
			"function methods:GetHidden() return getImmediate(self, 'hidden') end",
			"function methods:finishtweening() _actorFrameCancelTweens(self.Tag, true); self._delay = 0; self._duration = 0; return self end",
			"function methods:stoptweening() _actorFrameCancelTweens(self.Tag, false); self._delay = 0; self._duration = 0; return self end",
			"function methods:queuecommand(name) AF.playCommand(name, self); return self end",
			"function methods:playcommand(name) AF.playCommand(name, self); return self end",
			"function methods:cmd(commands) return AF.runCommands(self, commands) end",
			"function methods:setshader(shader) _actorFrameSetShader(self.Tag, shader); self.ShaderTag = shader; return self end",
			"function methods:GetShader()",
			"  local actor = self",
			"  return {",
			"    uniform1f = function(_, name, value) if actor.ShaderTag then setShaderFloat(actor.ShaderTag, name, value) end end,",
			"    uniform2f = function(_, name, x, y) if actor.ShaderTag then setShaderFloatArray(actor.ShaderTag, name, {x, y}) end end,",
			"    uniform3f = function(_, name, x, y, z) if actor.ShaderTag then setShaderFloatArray(actor.ShaderTag, name, {x, y, z}) end end",
			"  }",
			"end",
			"function methods:SetTarget(target) _actorFrameSetTarget(self.Tag, type(target) == 'table' and target.Tag or target); return self end",
			"function methods:target(target) return self:SetTarget(target) end",
			"function methods:SetWidth(v) setImmediate(self, 'width', v); return self end",
			"function methods:SetHeight(v) setImmediate(self, 'height', v); return self end",
			"function methods:Create() _actorFrameCapture(self.Tag); return self end",
			"function methods:GetTexture() return self.Tag end",
			"function methods:SetTexture(texture) setImmediate(self, 'texture', texture); return self end",
			"function methods:SetCaptureMode(mode) setImmediate(self, 'capturemode', mode); return self end",
			"function methods:SetCaptureInterval(seconds) setImmediate(self, 'captureinterval', seconds); return self end",
			"function methods:SetCaptureEveryFrame(enabled) setImmediate(self, 'captureeveryframe', enabled); return self end",
			"function methods:capture() _actorFrameCapture(self.Tag); return self end",
			"function methods:hibernate(t) return self:sleep(t) end",
			"function methods:SetInputPlayer(_) return self end",
			"function methods:SetAwake(_) return self end",
			"function methods:play() return self end",
			"function methods:pause() return self end",
			"local function command(spec, name)",
			"  return spec[name .. 'Command'] or spec[name]",
			"end",
			"local function run(actor, name, a, b)",
			"  if not actor then return end",
			"  local fn = command(actor.Spec or {}, name)",
			"  if type(fn) == 'function' then fn(actor, a, b) end",
			"  if name == 'Init' and actor.__StringInitCommand then AF.runCommands(actor, actor.__StringInitCommand) end",
			"  if name == 'On' and actor.__StringOnCommand then AF.runCommands(actor, actor.__StringOnCommand) end",
			"end",
			"local commandAliases = { hidden = 'hidden', visible = 'visible', x = 'x', y = 'y', z = 'z', xy = 'xy', zoom = 'zoom', zoomx = 'zoomx', zoomy = 'zoomy', basezoom = 'basezoom', basezoomx = 'basezoomx', basezoomy = 'basezoomy', zoomto = 'zoomto', zoomtowidth = 'zoomtowidth', zoomtoheight = 'zoomtoheight', stretchto = 'stretchto', rotationx = 'rotationx', rotationy = 'rotationy', rotationz = 'rotationz', diffuse = 'diffuse', diffusealpha = 'diffusealpha', sleep = 'sleep', linear = 'linear', accelerate = 'accelerate', decelerate = 'decelerate', bouncebegin = 'bouncebegin', bounceend = 'bounceend', spring = 'spring', queuecommand = 'queuecommand', playcommand = 'playcommand', finishtweening = 'finishtweening', stoptweening = 'stoptweening', aux = 'aux' }",
			"function AF.runCommands(actor, commands)",
			"  if not actor or type(commands) ~= 'string' then return actor end",
			"  for chunk in string.gmatch(commands, '([^;]+)') do",
			"    local parts = {}",
			"    for part in string.gmatch(chunk, '([^,]+)') do",
			"      part = tostring(part):gsub('^%s+', ''):gsub('%s+$', '')",
			"      if part ~= '' then parts[#parts + 1] = part end",
			"    end",
			"    local method = commandAliases[string.lower(parts[1] or '')]",
			"    if method and actor[method] then actor[method](actor, unpack(parts, 2)) end",
			"  end",
			"  return actor",
			"end",
			"local function runTree(actor, name, a, b)",
			"  run(actor, name, a, b)",
			"  if actor and actor.Children then",
			"    for _, child in ipairs(actor.Children) do runTree(child, name, a, b) end",
			"  end",
			"end",
			"local function create(spec, tag, parentTag, inheritedCamera)",
			"  AF._counter = AF._counter + 1",
			"  local kind = spec.__ActorFrameKind or 'ActorFrame'",
			"  local camera = spec.Camera or spec.camera or inheritedCamera or 'hud'",
			"  local actor = { Tag = tag, Name = spec.Name or tag, Parent = parentTag and AF.Actors[parentTag] or nil, Kind = kind, Spec = spec, Children = {}, _delay = 0, _duration = 0, _ease = 'linear' }",
			"  actor.ShaderTag = spec.Shader or spec.shader or spec.Frag or spec.frag",
			"  if type(spec.InitCommand or spec.initcommand) == 'string' then actor.__StringInitCommand = spec.InitCommand or spec.initcommand end",
			"  if type(spec.OnCommand or spec.oncommand) == 'string' then actor.__StringOnCommand = spec.OnCommand or spec.oncommand end",
			"  setmetatable(actor, { __index = methods })",
			"  AF.Actors[tag] = actor",
			"  publishName(actor)",
			"  _actorFrameCreate(kind, tag, parentTag, spec.Texture or spec.texture or spec.File or spec.file, spec.Text or spec.text, camera, spec.Width or spec.width or 1, spec.Height or spec.height or 1, spec.Color or spec.color or 'FFFFFF')",
			"  local props = { X = 'x', x = 'x', Y = 'y', y = 'y', Z = 'z', z = 'z', Alpha = 'alpha', alpha = 'alpha', DiffuseAlpha = 'alpha', diffusealpha = 'alpha', RotationZ = 'angle', rotationz = 'angle', Angle = 'angle', angle = 'angle', Zoom = 'zoom', zoom = 'zoom', BaseZoom = 'basezoom', basezoom = 'basezoom', ZoomX = 'zoomx', zoomx = 'zoomx', ZoomY = 'zoomy', zoomy = 'zoomy', Visible = 'visible', visible = 'visible', Hidden = 'hidden', hidden = 'hidden', Blend = 'blend', blend = 'blend', FollowTarget = 'followtarget', FollowTransform = 'followtransform', FollowVisuals = 'followvisuals', Capture = 'capturemode', CaptureMode = 'capturemode', CaptureInterval = 'captureinterval', CaptureEveryFrame = 'captureeveryframe' }",
			"  for from, to in pairs(props) do if spec[from] ~= nil then _actorFrameSet(tag, to, spec[from]) end end",
			"  if spec.Target or spec.target then _actorFrameSetTarget(tag, spec.Target or spec.target) end",
			"  if actor.ShaderTag then actor:setshader(actor.ShaderTag) end",
			"  if kind == 'ActorFrameTexture' then _actorFrameCapture(tag) end",
			"  if spec.Diffuse or spec.diffuse then _actorFrameSetColor(tag, spec.Diffuse or spec.diffuse) end",
			"  for _, childSpec in ipairs(spec) do",
			"    local childName = sanitize(childSpec.Name or ('actor' .. tostring(#actor.Children + 1)))",
			"    local child = create(childSpec, tag .. '.' .. childName, tag, camera)",
			"    table.insert(actor.Children, child)",
			"  end",
			"  if spec.__ActorFrameProxyWall and spec.Name then rawset(_G, tostring(spec.Name), actor.Children) end",
			"  return actor",
			"end",
			"local function forgetTree(actor)",
			"  if not actor then return end",
			"  AF.Actors[actor.Tag] = nil",
			"  if actor.Name then AF.Actors[tostring(actor.Name)] = nil end",
			"  if actor.Children then for _, child in ipairs(actor.Children) do forgetTree(child) end end",
			"end",
			"function AF.get(name)",
			"  local actor = AF.Actors[name]",
			"  if actor then return actor end",
			"  local tag = tostring(name or '')",
			"  if not tag:match('^actorframe%.') then tag = 'actorframe.' .. sanitize(tag) end",
			"  return AF.Actors[tag]",
			"end",
			"function AF.load(spec, name)",
			"  if type(spec) ~= 'table' then return nil end",
			"  local rootName = sanitize(name or spec.Name or 'default')",
			"  local rootTag = 'actorframe.' .. rootName",
			"  AF.destroy(rootTag, false)",
			"  local actor = create(spec, rootTag, nil, spec.Camera or spec.camera or 'hud')",
			"  AF.Roots[rootTag] = actor",
			"  runTree(actor, 'Init')",
			"  runTree(actor, 'On')",
			"  return actor",
			"end",
			"function AF.destroy(name, runOff)",
			"  local tag = tostring(name or 'actorframe.default')",
			"  if not tag:match('^actorframe%.') then tag = 'actorframe.' .. sanitize(tag) end",
			"  local actor = AF.Roots[tag]",
			"  if runOff ~= false then runTree(actor, 'Off') end",
			"  AF.Roots[tag] = nil",
			"  forgetTree(actor)",
			"  return _actorFrameDestroy(tag)",
			"end",
			"function AF.destroyAll(runOff)",
			"  for tag, actor in pairs(AF.Roots) do if runOff ~= false then runTree(actor, 'Off') end; _actorFrameDestroy(tag); AF.Roots[tag] = nil; forgetTree(actor) end",
			"end",
			"function AF.playCommand(name, root)",
			"  name = tostring(name or ''):gsub('Command$', '')",
			"  if type(root) == 'table' and root.Tag then runTree(root, name); return true end",
			"  if root then",
			"    local tag = tostring(root)",
			"    if not tag:match('^actorframe%.') then tag = 'actorframe.' .. sanitize(tag) end",
			"    runTree(AF.Roots[tag], name)",
			"    return AF.Roots[tag] ~= nil",
			"  end",
			"  for _, actor in pairs(AF.Roots) do runTree(actor, name) end",
			"  return true",
			"end",
			"function AF.loadXML(path) debugPrint('ActorFrame.loadXML is reserved for a future XML importer: ' .. tostring(path)); return false end",
			"function AF.__update(elapsed) for _, actor in pairs(AF.Roots) do runTree(actor, 'Update', elapsed) end end",
			"function AF.__beat(beat) for _, actor in pairs(AF.Roots) do runTree(actor, 'Beat', beat) end end",
			"function AF.__step(step) for _, actor in pairs(AF.Roots) do runTree(actor, 'Step', step) end end",
			"function AF.__destroyAll() AF.destroyAll(true) end"
		].join("\n");
	}

	public static function hookInstaller():String
	{
		return [
			"if ActorFrame and not ActorFrame.__hooksInstalled then",
			"  ActorFrame.__hooksInstalled = true",
			"  local oldUpdate = _G.onUpdate",
			"  _G.onUpdate = function(elapsed)",
			"    local ret = nil",
			"    if oldUpdate then ret = oldUpdate(elapsed) end",
			"    if ActorFrame.__update then ActorFrame.__update(elapsed) end",
			"    return ret or Function_Continue",
			"  end",
			"  local oldBeat = _G.onBeatHit",
			"  _G.onBeatHit = function()",
			"    local ret = nil",
			"    if oldBeat then ret = oldBeat() end",
			"    if ActorFrame.__beat then ActorFrame.__beat(curBeat) end",
			"    return ret or Function_Continue",
			"  end",
			"  local oldStep = _G.onStepHit",
			"  _G.onStepHit = function()",
			"    local ret = nil",
			"    if oldStep then ret = oldStep() end",
			"    if ActorFrame.__step then ActorFrame.__step(curStep) end",
			"    return ret or Function_Continue",
			"  end",
			"  local oldDestroy = _G.onDestroy",
			"  _G.onDestroy = function()",
			"    local ret = nil",
			"    if oldDestroy then ret = oldDestroy() end",
			"    if ActorFrame.__destroyAll then ActorFrame.__destroyAll() end",
			"    return ret or Function_Continue",
			"  end",
			"end"
		].join("\n");
	}
}
#end
