name: Missing documentation
description: Ask for documentation of web page if something is missing.
labels: [documentation]
body:
  - type: textarea
    attributes:
      label: What needs to be documented?
      description: 'For example: "There is no another preview video of modchart NotITG"'
    validations:
      required: true